DATA_FOLDER_PATH = "../DATA"

GAMES_FILE_PATH = DATA_FOLDER_PATH + "/games.csv"

TURNS_FILE_PATH = DATA_FOLDER_PATH + "/turns.csv"

TRAIN_FILE_PATH = DATA_FOLDER_PATH + "/train.csv"

TEST_FILE_PATH = DATA_FOLDER_PATH + "/test.csv"